--- 
abstract: Fill a HTML::FormFu form from the database and vice-versa
author: Carl Franks
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-HTML-FormFu
no_index: 
  directory: 
    - inc
    - t
requires: 
  DBIx::Class: 0
  HTML::FormFu: 0
version: 0.01002
